### ISSUE TITLE
Crash a l'utilisation du Carpenter

### ISSUE THREAD

**Issue by DrumSlayers** [exitedprotek/Nodejs-Minecraft-Launcher#6]
Le jeu Plante quand on ouvre le GUI du carpenter
Aucun moyen de craft les items le necesitant
PS: Je ne suis pas le seul , on est 3 a avoir le probleme

**Comment by jsunier** [comment]
Je vais voir si une mise à jour est disponible

**Comment by DrumSlayers** [comment]
Issue fermée , mais problème toujours present
